**Using Naive Baye's checked whether email is spam or not**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df= pd.read_csv("spam.csv")

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [7]:
df['spam']= df["Category"].apply(lambda x: 1 if x=="spam" else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test= train_test_split(df.Message, df.spam, test_size=0.25)

In [16]:
#count vectorizer tachnique used to convert test into numbers

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
x_train_count=v.fit_transform(x_train.values)
x_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
from sklearn.naive_bayes import MultinomialNB
model= MultinomialNB()


In [21]:
#here x_train_count is the text we convert into numbers
model.fit(x_train_count, y_train)

MultinomialNB()

In [22]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [24]:
#x_test bhi text me hi hai so convert / transform it 
x_test_count= v.transform(x_test)
model.score(x_test_count, y_test)

0.9813352476669059

In [25]:
#Sklearn pipeline use for transformation

from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [26]:
#now we cann now direct train on x_train, nd y_train

clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [27]:
clf.score(x_test,y_test)

0.9813352476669059

In [28]:
#jo wahan 2 emails check kri thi yahan pass krke check krke dekh lo
clf.predict(emails)

array([0, 1], dtype=int64)